# This workflow will build and test a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven, Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install with Maven
      run: mvn install
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM
      run: npm install
      working-directory: ./frontend-src
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn compile
    
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build NPM
      run: npm build
      working-directory: ./frontend-src
      
  test:
    runs-on: ubuntu-latest   
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Test
      run: mvn clean test
      
   # - uses: actions/checkout@v2
   # - name: Use Node.js ${{ matrix.node-version }}
   #   uses: actions/setup-node@v1
   #   with:
   #     node-version: ${{ matrix.node-version }}
   # - name: NPM Test
   #   run: npm test
   #   env:
   #     CI: true
     
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Result
        # Directory containing files to upload
        path: ./artifact/results
