# This workflow will build and test a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI for Maven, Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mvn_install_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install with Maven
      run: mvn install
    - name: Build with Maven
      run: mvn compile
      
  mvntest:
    runs-on: ubuntu-latest
    needs: [mvn_install_build] 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Test
      run: mvn clean test
  
  
  npm_install_build_test:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM
      run: npm ci 
      working-directory: ./frontend-src
    - name: Build NPM
      run: npm build
      working-directory: ./frontend-src  
    - name: Karma
      run: npm install karma --save-dev
      working-directory: ./frontend-src
    - name: NPM Test
      run: npx ng test --watch=false --browsers ChromeHeadless
      #env:
      #  CI: true
      working-directory: ./frontend-src
    - uses: actions/checkout@v1
    - run: npm install compodoc --save-dev
    - run: npx compodoc -p tsconfig.app.json
      working-directory: ./frontend-src 
    - name: Upload compodoc artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Compodoc artifact
        path: ./frontend-src/documentation
    - uses: actions/checkout@v1
    - run: npm install prettier
    - run: npx prettier@2.0.4 . --write
    - run: npx prettier@2.0.4 . --check > ./frontend-src/prettier-result.txt
    - name: Upload prettier artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Prettier artifact
        path: ./frontend-src/prettier-result.txt
